"""Frozen entry point.

PyInstaller can be pointed at a console script, but the indirection makes
tracebacks harder to read and the script wrapper is regenerated by pip on every
install. A three-line module of our own is stable and obvious.

``freeze_support`` is called because numpy may spawn helper processes on
Windows; without it a frozen child re-runs the whole app instead of the worker.
"""

from __future__ import annotations

import multiprocessing
import sys


def main() -> None:
    multiprocessing.freeze_support()

    # A frozen exe inherits whatever code page the console happens to be in.
    # spektr draws with braille and box-drawing characters, so force UTF-8 on
    # the streams before anything prints — otherwise --list-themes and the
    # plugin CLI raise UnicodeEncodeError on a default Windows console.
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            try:
                stream.reconfigure(encoding="utf-8", errors="replace")
            except Exception:
                pass

    from spektr.app import main as run

    run()


if __name__ == "__main__":
    main()
