"""Regenerate spektr/catalog.py from the live mode registry.

The catalogue lets the picker, ``--list-modes``, loadouts and shuffle know
every mode's name, group and blurb without importing a single mode module —
which is what lets a mode's code load only when it is first used. Importing
all of them costs 659 ms and 12 MB at startup today.

Run it after adding, renaming or removing a mode:

    python tools/build_catalog.py

``tests/test_catalog.py`` fails if the file and the registry disagree, so a
forgotten run is caught rather than silently shipping a stale list.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import spektr.modes as M  # noqa: E402

TARGET = ROOT / "spektr" / "catalog.py"

HEADER = '''"""Every built-in mode, without importing any of them.

Generated by ``tools/build_catalog.py`` — do not edit by hand. Each entry is
``(name, group, blurb, hidden, module)``, where ``module`` names the file
under :mod:`spektr.modes` that registers the mode and is what a lazy import
loads when that mode is first used.

``tests/test_catalog.py`` checks this against the real registry.
"""
from __future__ import annotations

#: name, group, blurb, hidden, module
CATALOG: tuple[tuple[str, str, str, bool, str], ...] = (
'''

FOOTER = ''')


def names() -> list[str]:
    return [row[0] for row in CATALOG]


def module_for(name: str) -> str | None:
    """Which mode module registers ``name``, or None if it is not built in."""
    for row in CATALOG:
        if row[0] == name:
            return row[4]
    return None
'''


def rows() -> list[tuple[str, str, str, bool, str]]:
    # Every module in the package, not just the ones the catalogue already
    # names: those are all ``load_all`` can reach, so a new mode module would
    # otherwise never make it into the catalogue that is the only way in.
    import importlib
    import pkgutil

    for info in pkgutil.iter_modules(M.__path__):
        importlib.import_module(f"{M.__name__}.{info.name}")
    M.load_all()
    return [
        (m.name, m.group, m.blurb, m.hidden, m.fn.__module__.split(".")[-1])
        for m in M.MODES
        if m.plugin is None
    ]


def main() -> int:
    lines = [HEADER]
    for name, group, blurb, hidden, module in rows():
        lines.append(f"    ({name!r}, {group!r}, {blurb!r}, {hidden!r}, {module!r}),\n")
    lines.append(FOOTER)
    TARGET.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {len(rows())} modes to {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
