"""Every built-in mode, without importing any of them.

Generated by ``tools/build_catalog.py`` — do not edit by hand. Each entry is
``(name, group, blurb, hidden, module)``, where ``module`` names the file
under :mod:`spektr.modes` that registers the mode and is what a lazy import
loads when that mode is first used.

``tests/test_catalog.py`` checks this against the real registry.
"""
from __future__ import annotations

#: name, group, blurb, hidden, module
CATALOG: tuple[tuple[str, str, str, bool, str], ...] = (
    ('Bars', 'spectrum', 'the classic — ten-ish bars with peak markers', False, 'spectrum'),
    ('Bricks', 'spectrum', 'chunky, no partial cells', False, 'spectrum'),
    ('Columns', 'spectrum', 'gapless, interpolated across the full width', False, 'spectrum'),
    ('Ladder', 'spectrum', 'segmented LED stack', False, 'spectrum'),
    ('Mirror', 'spectrum', 'grows out from the centre line', False, 'spectrum'),
    ('Readout', 'spectrum', 'scrolling numeric ticker, band levels as plain digits', False, 'spectrum'),
    ('Stereo', 'stereo', 'per-band L/R meters, mirrored from centre', False, 'spectrum'),
    ('Wave', 'scope', 'smoothed waveform', False, 'scope'),
    ('Scope', 'scope', 'trigger-synced oscilloscope — the trace holds still', False, 'scope'),
    ('Scope (o)', 'scope', 'the same trace as a continuous stroke — needs a terminal that draws Unicode 16 octants', True, 'scope'),
    ('ECG', 'scope', 'scrolling trace, like a heart monitor', False, 'scope'),
    ('ECG (o)', 'scope', 'the same scrolling trace, drawn solid — needs a terminal that draws Unicode 16 octants', True, 'scope'),
    ('Strings', 'scope', 'plucked strings, bowed by their own band', False, 'scope'),
    ('Helix', 'stereo', 'two strands rotating around a shared axis, split by true L/R phase', False, 'scope'),
    ('Gonio', 'stereo', 'stereo phase scope with phosphor trail', False, 'scope'),
    ('Scatter', 'particles', "density sparkle, thicker where it's loud", False, 'particles'),
    ('Flame', 'particles', 'fire, licking upward from each band', False, 'particles'),
    ('Pulse', 'particles', 'a radial blob with shockwaves thrown off the beat', False, 'particles'),
    ('Arcs', 'particles', 'hollow rings, one per band, pushed out by level', False, 'particles'),
    ('Bubbles', 'particles', 'bubbles from the low end, popping at the top', False, 'particles'),
    ('Radial', 'particles', 'the spectrum wrapped into a circle', False, 'particles'),
    ('Radial (o)', 'particles', 'the same ring as a solid field at two colours a cell — needs a terminal that draws Unicode 16 octants', True, 'particles'),
    ('Sonar', 'particles', 'one sweep, not the whole spectrum — returns fade like CRT phosphor', False, 'particles'),
    ('Sonar (o)', 'particles', 'the same sweep drawn solid instead of stippled — needs a terminal that draws Unicode 16 octants', True, 'particles'),
    ('Orbit', 'particles', 'bodies on real elliptical orbits; loud bands swing out', False, 'particles'),
    ('Fireworks', 'particles', 'beat-triggered launches, bursts, and fall', False, 'particles'),
    ('Dune', 'particles', 'sand piles up by band, avalanching past a threshold', False, 'particles'),
    ('Murmuration', 'particles', 'a flock wheeling and scattering with the beat', False, 'particles'),
    ('Retro', 'scenes', 'sunset grid, with the spectrum as the horizon', False, 'scenes'),
    ('Auroras', 'scenes', 'a light ribbon whose lower rim rides the spectrum', False, 'scenes'),
    ('Keys', 'scenes', 'a lit keyboard; struck bands scroll away as falling notes', False, 'scenes'),
    ('Tunnel', 'scenes', 'flying down a pipe, ribbed by the beat', False, 'scenes'),
    ('Tunnel In', 'scenes', 'rings thrown out of the centre on the beat, rushing past you', False, 'scenes'),
    ('Crosscurrent', 'scenes', 'a spinning tunnel of two ring streams, rushing out and drawn in, flickering on the beat', False, 'scenes'),
    ('Warp', 'scenes', 'starfield, accelerating with the music', False, 'scenes'),
    ('Matrix', 'scenes', "digital rain, falling faster when it's loud", False, 'scenes'),
    ('Boot', 'scenes', 'an old PC waking up — BIOS POST, a boot log, a blinking cursor', False, 'scenes'),
    ('Spectro', 'fields', 'scrolling waterfall — frequency up, time across', False, 'field_spectral'),
    ('Plasma', 'fields', 'solid colour field, warped by the spectrum', False, 'field_spectral'),
    ('Plasma (o)', 'fields', 'the same field at eight samples a cell instead of two — needs Unicode 16 octants', True, 'field_spectral'),
    ('Chladni', 'fields', 'nodal interference pattern, plate modes set by the dominant pitch', False, 'field_chladni'),
    ('Chladni (o)', 'fields', 'the same plate at eight samples a cell, nodal lines antialiased — needs Unicode 16 octants', True, 'field_chladni'),
    ('Chladni Flow', 'fields', 'a plate figure melting continuously from one resonance into the next', False, 'field_chladni'),
    ('Chladni Flow (o)', 'fields', 'the melting plate at eight samples a cell — needs Unicode 16 octants', True, 'field_chladni'),
    ('Chladni Extreme', 'fields', 'a plate driven past its modes - morphs, escalates, and snaps on the beat', False, 'field_chladni'),
    ('Chladni Extreme (o)', 'fields', 'the overdriven plate at eight samples a cell — needs Unicode 16 octants', True, 'field_chladni'),
    ('VFD', 'fields', 'vacuum-fluorescent bargraph with phosphor afterglow', False, 'field_meters'),
    ('Needle', 'stereo', 'analogue VU — one sweeping needle, one red zone', False, 'field_meters'),
    ('VU', 'stereo', 'big L/R LED meters with peak hold', False, 'field_meters'),
    ('Kaleidoscope', 'fields', 'a mirrored tube of stained glass — the wedge count follows the spectrum, beats shake the chamber', False, 'field_kaleidoscope'),
    ('Kaleidoscope (o)', 'fields', 'the same tube at four times the vertical detail — needs a terminal that draws Unicode 16 octants', True, 'field_kaleidoscope'),
    ('Kaleidoscope Ultra (o)', 'fields', 'the tube with its seams antialiased — the smoothest a terminal gets', True, 'field_kaleidoscope'),
    ('Dither', 'fields', 'the spectrum printed as a newspaper halftone, in one-bit crosshatch', False, 'field_dither'),
    ('Dither Storm', 'fields', "Dither's one-bit crosshatch, but the field moves — each band drives its own wave, and beats throw rings through it", False, 'halftone'),
    ('Dither Storm Extreme', 'fields', 'Dither Storm with nothing holding it back — hits pile up and a dense passage blows the field to white', False, 'halftone'),
    ('Valentine', 'fields', 'a heart that beats with the track, trailing smaller ones upward', False, 'field_hearts'),
    ('Valentine (o)', 'fields', 'the same heart drawn solid instead of stippled — needs a terminal that draws Unicode 16 octants', True, 'field_hearts'),
    ('Locket', 'fields', 'an outlined heart, pulsing rings of hearts outward on the beat', False, 'field_hearts'),
    ('Locket Beat', 'fields', 'the locket heart, throwing exactly one ring on every beat', False, 'field_hearts'),
    ('Maelstrom', 'fields', 'a real fluid sim, stirred by the music', False, 'maelstrom'),
    ('Maelstrom (o)', 'fields', 'the same fluid as a solid field at two colours a cell — needs a terminal that draws Unicode 16 octants', True, 'maelstrom'),
    ('Vinyl', 'lofi', 'a record whose grooves light up as a radial spectrum', False, 'lofi'),
    ('Rain', 'lofi', "rain on the glass, falling harder when it's loud", False, 'lofi'),
    ('Snow', 'lofi', 'snowfall in three planes, thickening and gusting with the track', False, 'lofi'),
    ('Ember', 'lofi', 'a coal bed burning by band, sparks rising off the hot spots', False, 'lofi'),
    ('Swell', 'terrain', 'an open sea in half-tones — built for the Android terrain view', False, 'terrain'),
    ('Shooting Star', 'cosmos', 'a night sky, with meteors thrown from a drifting radiant on the beat', False, 'cosmos'),
    ('Constellations', 'cosmos', 'beats draw lines between fixed stars, then the figures fade', False, 'cosmos'),
    ('Star Trails', 'cosmos', 'a long exposure: the sky turns, and the arcs it leaves are the show', False, 'cosmos'),
    ('Supernova', 'cosmos', 'a mostly dark sky, waiting for the one hit worth a catastrophe', False, 'cosmos'),
    ('JP Bars', 'jp', 'a segmented LED meter whose bars peel off and rise as they fall away', False, 'jp'),
    ('JP Drift', 'jp', 'the meter shedding bulbs: they break off the top and fall, piling at the foot', False, 'jp'),
    ('JP Pulse', 'jp', 'the meter bent into a ring — a spoke of bulbs per band, chased on the beat', False, 'jp'),
    ('JP Sequencer', 'jp', 'the meter paged by the bar — four pages, one live, three holding their beat', False, 'jp_music'),
    ('JP Demo', 'jp', 'a head-unit demo sunburst: kicks blast it outward, snares turn it, hats twinkle the tips', False, 'jp_music'),
    ('JP Clock', 'jp', 'a clock face that keeps the bar: the hand writes each bar in, the last four step inward', False, 'jp_music'),
    ('JP Ribbons', 'jp', "three flowing ribbons of segments — the kick's, the snare's and the hats' — locked to the bar", False, 'jp_music'),
    ('None', 'off', 'nothing at all', False, 'modes'),
)


def names() -> list[str]:
    return [row[0] for row in CATALOG]


def module_for(name: str) -> str | None:
    """Which mode module registers ``name``, or None if it is not built in."""
    for row in CATALOG:
        if row[0] == name:
            return row[4]
    return None
